### ISSUE TITLE
Query-to-reference mapping

### ISSUE THREAD

**Issue by maarten-devries** [eleozzr/scDML#2]
Thank you for the very interesting package. I have a question: do you have plans to extend the functionality of scDML to include query-to-reference mapping?

**Comment by yuxiaokang-source** [comment]
Thank you for your suggesttions,  I will try to implement the functionality and run some tests include query-to-reference with scDML  in the future

**Comment by M0hammadL** [comment]
hi @yuxiaokang-source  happy to chat and include as part of searches supported models
