### ISSUE TITLE
An error when running scDML.

### ISSUE THREAD

**Issue by derekchen7** [eleozzr/scDML#5]
Hello, 
Recently, an error is bothering me when I use scDML to intergrate my sc-RNA data. 
It appears when I running the following codes:

if os.path.isfile(os.path.join(scdml.save_dir,"scDML_model.pkl")):
    os.remove(os.path.join(scdml.save_dir,"scDML_model.pkl"))
    
features=scdml.train(expect_num_cluster=None)
adata.obsm["X_emb"]=features
adata.obs["reassign_cluster"]=scdml.train_label.astype(int).astype(str)
adata.obs["reassign_cluster"]=adata.obs["reassign_cluster"].astype("category")

And the error is:
 
2023-10-02 13:45:41,594 - root - INFO - Optimal number of clusters [ 5 10 13 17 26]
2023-10-02 13:45:41,595 - root - INFO - scDML can't find the mering result of cluster=5 ,you can run merge_cluster(fixed_ncluster=5) function to get this

Sometimes I restart the jupyter nootbook and re-run the code solves this error. But sometimes it keep going wrong. 
I'd like to know what is going on when this appear and what should I do to solve it.
Thanks.

**Comment by derekchen7** [comment]
I also tried to run the following code as the error information noticed

scdml.merge_cluster(fixed_ncluster=5)

However, this gives a new error:

TypeError: merge_cluster() got an unexpected keyword argument 'fixed_ncluster'

**Comment by yuxiaokang-source** [comment]
> I also tried to run the following code as the error information noticed
> 
> scdml.merge_cluster(fixed_ncluster=5)
> 
> However, this gives a new error:
> 
> TypeError: merge_cluster() got an unexpected keyword argument 'fixed_ncluster'

Thank you for your information,
you can try 
```
ncluster=5;
scdml.integrate(adata,batch_key="BATCH",ncluster_list=[ncluster],
               expect_num_cluster=ncluster,merge_rule="rule2")
```
`

**Comment by yuxiaokang-source** [comment]
> Hello, Recently, an error is bothering me when I use scDML to intergrate my sc-RNA data. It appears when I running the following codes:
> 
> if os.path.isfile(os.path.join(scdml.save_dir,"scDML_model.pkl")): os.remove(os.path.join(scdml.save_dir,"scDML_model.pkl"))
> 
> features=scdml.train(expect_num_cluster=None) adata.obsm["X_emb"]=features adata.obs["reassign_cluster"]=scdml.train_label.astype(int).astype(str) adata.obs["reassign_cluster"]=adata.obs["reassign_cluster"].astype("category")
> 
> And the error is:
> 
> 2023-10-02 13:45:41,594 - root - INFO - Optimal number of clusters [ 5 10 13 17 26] 2023-10-02 13:45:41,595 - root - INFO - scDML can't find the mering result of cluster=5 ,you can run merge_cluster(fixed_ncluster=5) function to get this
> 
> Sometimes I restart the jupyter nootbook and re-run the code solves this error. But sometimes it keep going wrong. I'd like to know what is going on when this appear and what should I do to solve it. Thanks.

what about running with python script(`.py`)

**Comment by derekchen7** [comment]
> > I also tried to run the following code as the error information noticed
> > scdml.merge_cluster(fixed_ncluster=5)
> > However, this gives a new error:
> > TypeError: merge_cluster() got an unexpected keyword argument 'fixed_ncluster'
> 
> Thank you for your information, you can try
> 
> ```
> ncluster=5;
> scdml.integrate(adata,batch_key="BATCH",ncluster_list=[ncluster],
>                expect_num_cluster=ncluster,merge_rule="rule2")
> ```
> 
> `

Thanks for your immediate reply. This code works. And my problem has been solved.
