### ISSUE TITLE
merge_rule2

### ISSUE THREAD

**Issue by Chengwei-Yan** [eleozzr/scDML#7]
Dear author, sometimes during runtime, it gets stuck at the "merge_rule2" section. What could be the reason for this?

**Comment by yuxiaokang-source** [comment]
> Dear author, sometimes during runtime, it gets stuck at the "merge_rule2" section. What could be the reason for this?

Thank you for trying our tools. Could give me more details about the error?  For example, could you show me the code and dataset to reproduce the bug ? Because I haven't encounted the problem before, I can't figure out what happened without your code and dataset.  If the tested dataset is large, you can send the dataset to my email(yuxiaokang2018@163.com). I will  try my best to solve the problem.

**Comment by Chengwei-Yan** [comment]
> > Dear author, sometimes during runtime, it gets stuck at the "merge_rule2" section. What could be the reason for this?
> 
> Thank you for trying our tools. Could give me more details about the error? For example, could you show me the code and dataset to reproduce the bug ? Because I haven't encounted the problem before, I can't figure out what happened without your code and dataset. If the tested dataset is large, you can send the dataset to my email([yuxiaokang2018@163.com](mailto:yuxiaokang2018@163.com)). I will try my best to solve the problem.

Dear author,

It seems I've encountered an issue. Before running, I set `ncluster_list` as a list containing multiple values. By default, I set it to range from 1 to 20. However, I found that removing the value 1 from this list resolved the problem of it getting stuck. Interestingly, I haven't encountered this error when testing with other datasets using the default range from 1 to 20. So, I'm puzzled as to why this bug occurs. It appears that `ncluster_list` cannot contain the value 1 for certain datasets. Thank you for your response.

**Comment by Chengwei-Yan** [comment]
Dear author,

I have a further update. Previously, I set the `ncluster_list` to range from 1 to 20 because setting it to specific values sometimes resulted in errors like "Optimal number of clusters [ x x x x]". Hence, I opted for a broader range to avoid this bug. However, when I switched to a different preprocessing method for the same dataset, I found that using the range from 1 to 20  led to errors.

**Comment by yuxiaokang-source** [comment]
> Dear author,
> 
> I have a further update. Previously, I set the `ncluster_list` to range from 1 to 20 because setting it to specific values sometimes resulted in errors like "Optimal number of clusters [ x x x x]". Hence, I opted for a broader range to avoid this bug. However, when I switched to a different preprocessing method for the same dataset, I found that using the range from 1 to 20 led to errors.

Thank you for your information, it's look very strange,  I can't give you any useful suggestions now , because I don't know why this happens either😆. Maybe you can provide me a jupyter notebook to reproduce the bug, so I can debug the source code in detail.

**Comment by Chengwei-Yan** [comment]
> > Dear author,
> > I have a further update. Previously, I set the `ncluster_list` to range from 1 to 20 because setting it to specific values sometimes resulted in errors like "Optimal number of clusters [ x x x x]". Hence, I opted for a broader range to avoid this bug. However, when I switched to a different preprocessing method for the same dataset, I found that using the range from 1 to 20 led to errors.
> 
> Thank you for your information, it's look very strange, I can't give you any useful suggestions now , because I don't know why this happens either😆. Maybe you can provide me a jupyter notebook to reproduce the bug, so I can debug the source code in detail.

Hello,

I will send you the ipynb file later, but I may not be able to do it promptly due to some work I have to finish first. I believe the possible error could be that I noticed when the first element in "optimal clusters" is 1 and expect_num_cluster=None, it may lead to this error. The reason for this error is that the data I used is not single-cell data but other data that requires batch effect removal. Therefore, the estimated number of clusters may not represent multiple cell types but possibly only one type.

**Comment by yuxiaokang-source** [comment]
OK, you can send me the ipynb and test data in your free time.  Don't hesitate to contact me if you have any questions about the package.  Happy to chat😊
